[package]
name = "variables"
version = "0.1.0"
authors = ["hongmaoxiao <769501294@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
